version: "3.8"

# Docker Compose configuration for Render.com-style deployments
# This example shows how to configure Focalboard using only environment variables
# Perfect for cloud platforms that provide DATABASE_URL and don't support volume mounting

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: focalboard-render
    ports:
      - "8000:8000"
    environment:
      # Database Configuration (use DATABASE_URL for cloud platforms)
      # Render.com and similar platforms provide this automatically
      - DATABASE_URL=postgres://user:password@host:5432/database
      
      # Alternative: Manual database configuration
      # - FOCALBOARD_DBTYPE=postgres
      # - FOCALBOARD_DBCONFIG=postgres://user:password@host:5432/database?sslmode=require

      # Server Configuration
      - FOCALBOARD_SERVERROOT=https://your-app.onrender.com
      - FOCALBOARD_PORT=8000
      - FOCALBOARD_USESSL=true
      - FOCALBOARD_SECURECOOKIE=true

      # File Storage Configuration
      # Option 1: Local storage (files will be lost on redeploy)
      - FOCALBOARD_FILESDRIVER=local
      - FOCALBOARD_FILESPATH=./data/files
      
      # Option 2: S3 storage (recommended for production)
      # - FOCALBOARD_FILESDRIVER=s3
      # - FOCALBOARD_FILESS3CONFIG_BUCKET=my-focalboard-bucket
      # - FOCALBOARD_FILESS3CONFIG_REGION=us-west-2
      # - FOCALBOARD_FILESS3CONFIG_ACCESSKEYID=your-access-key
      # - FOCALBOARD_FILESS3CONFIG_SECRETACCESSKEY=your-secret-key
      # - FOCALBOARD_FILESS3CONFIG_SSL=true

      # Application Settings
      - FOCALBOARD_TELEMETRY=false
      - FOCALBOARD_AUTHMODE=native
      - FOCALBOARD_SESSIONEXPIRETIME=1209600  # 2 weeks
      - FOCALBOARD_SESSIONREFRESHTIME=18000   # 5 hours
      - FOCALBOARD_ENABLELOCALMODE=false
      
      # Security Settings
      - FOCALBOARD_ENABLEPUBLICSHAREDBOARDS=false
      
      # Optional: Webhooks (comma-separated)
      # - FOCALBOARD_WEBHOOKUPDATE=https://webhook1.com,https://webhook2.com
      
      # Optional: Feature Flags (key:value pairs)
      # - FOCALBOARD_FEATUREFLAGS=feature1:true,feature2:enabled
      
      # Optional: Monitoring
      # - FOCALBOARD_PROMETHEUSADDRESS=:9092

    # No volumes needed - everything is configured via environment variables
    # Data persists in the external database (PostgreSQL)
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/system/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s